#!/bin/bash

echo "REMOVING SITES..."
rm -frv magento.1*
/Applications/MAMP/Library/bin/mysql -uroot -proot -v -e "DROP DATABASE IF EXISTS magento1400;
DROP DATABASE IF EXISTS magento1401;
DROP DATABASE IF EXISTS magento1410;
DROP DATABASE IF EXISTS magento1411;
DROP DATABASE IF EXISTS magento1420;
DROP DATABASE IF EXISTS magento1501;
DROP DATABASE IF EXISTS magento1510;
DROP DATABASE IF EXISTS magento1600;
DROP DATABASE IF EXISTS magento1610;
DROP DATABASE IF EXISTS magento1620;
DROP DATABASE IF EXISTS magento1700;
DROP DATABASE IF EXISTS magento1702;"